name: Publish PowerShell Module

on:
  push:
    branches: [ master ]

jobs:
  publish-to-gallery:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      shell: pwsh
      run: |
        .\build\build.ps1
        Publish-Module -Path .\M365Reporting -NuGetApiKey $env:NUGET_KEY -Verbose
